### ISSUE TITLE
clash for windows报错：invalid dns enhanced-mode:redir-host

### ISSUE THREAD

**Issue by KnifeOfLife** [peasoft/NoMoreWalls#14]
每次要手动将dns.enhanced-mode从redir-host改成fake-ip

**Comment by peasoft** [comment]
原版 Clash 不支持 `redir-host`，建议改用 Clash-Verge-rev 并使用 Clash.Meta (mihomo) 内核，因为 Clash 和 CFW 本身也都停更了。不过为了兼容性我还是修一下吧。
