### ISSUE TITLE
zhihu知乎为什么放在了广告拦截中

### ISSUE THREAD

**Issue by iyzgit** [peasoft/NoMoreWalls#18]
zhihu知乎为什么放在了广告拦截中

**Comment by peasoft** [comment]
> 知乎在中国大陆境内因未知原因只能获取乱码内容，无法正常浏览，因此我们将其加入了广告拦截列表以节省流量。何时移除取决于网站何时恢复正常，我们会密切关注这一情况。

在 README.md 中已说明。由于该现象得到缓解，稍后我会将其移出广告拦截。

**Comment by MarvinXu** [comment]
小红书和豆瓣呢？

**Comment by peasoft** [comment]
不可以。
________________________________
发件人: Marvin ***@***.***>
发送时间: 2025年9月30日 11:25
收件人: peasoft/NoMoreWalls ***@***.***>
抄送: Pea Soft ***@***.***>; State change ***@***.***>
主题: Re: [peasoft/NoMoreWalls] zhihu知乎为什么放在了广告拦截中 (Issue #18)

[https://avatars.githubusercontent.com/u/7382357?s=20&v=4]MarvinXu left a comment (peasoft/NoMoreWalls#18)<https://github.com/peasoft/NoMoreWalls/issues/18#issuecomment-3349797270>

可以加个分组吗？把这些内容和广告区分开

―
