### ISSUE TITLE
链接1

### ISSUE THREAD

**Issue by wanghaisheng** [peasoft/NoMoreWalls#2]
![image](https://github.com/peasoft/NoMoreWalls/assets/2363295/47997407-3639-44f5-ba1b-f4f0db993259)

**Comment by peasoft** [comment]
我有空处理下，实在不行要不先用下 V2rayU 吧，等我修好了再换回 Clash。

**Comment by peasoft** [comment]
我试着修复了一下，暂时没有问题，如果再出现问题请 reopen 这个 issue，如果一两个月没问题我就把复核标签去掉。
