### ISSUE TITLE
提前重复过滤功能

### ISSUE THREAD

**Issue by wukan1986** [peasoft/NoMoreWalls#23]
配合v2rayNG 1.8.39版，每次都有10~12条重复，它是别名不同参数相同。
建议提前对重复节点过滤

**Comment by peasoft** [comment]
抱歉，最近比较忙，现在才看到。事实上，本项目是全网为数不多支持提前重复过滤的。这些看似相同的节点可能在端口、用户名和密码、伪装的 SNI 等细节不同。本项目在去重时会将细节有差异的节点区分出来，而 v2rayNG 不会，这是两个程序去重标准的不同导致。

**Comment by wukan1986** [comment]
谢谢！

v2rayNG 1.9.x版对重复过滤功能做了调整，导致去重功能失效。在我提出后，他又在1.9.18中做了修复。
所以，你的项目去重的优先级不是那么重要了。

https://github.com/2dust/v2rayNG/issues/3948
