### ISSUE TITLE
我想请问下，如何在代码中让它自动更改自己需要的节点名称

### ISSUE THREAD

**Issue by ClodQiu** [peasoft/NoMoreWalls#7]
我想请问下，如何在代码中让它自动更改自己需要的节点名称
希望能得到你的回复！

**Comment by peasoft** [comment]
在 [第 801 行](https://github.com/peasoft/NoMoreWalls/blob/8612c45027fe67f01ee3c76f14c6a7fda46491f2/fetch.py#L801) 后加入 `p.data['name'] = "节点名称"`

**Comment by peasoft** [comment]
还有，802 \~ 804 行要删了，这是我调试用的。

**Comment by ClodQiu** [comment]
非常感谢！
