### ISSUE TITLE
代理类型不支持

### ISSUE THREAD

**Issue by errorduplicator** [peasoft/NoMoreWalls#8]
我用的Clash for Windows不支持hysteria、hysteria2和tuic怎么办？
![CFW](https://github.com/peasoft/NoMoreWalls/assets/135431383/35c5982b-07ef-4427-bb60-84caf6ffbc0c)

**Comment by peasoft** [comment]
抱歉，程序出问题了，这些本来是 Clash Meta 专用的节点，不知怎么跑到原版 Clash 的订阅里了。我修一下。
